# Generated by Django 2.2.1 on 2020-07-04 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Example1', '0002_auto_20200703_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example1',
            name='age',
            field=models.IntegerField(max_length=2),
        ),
    ]
